#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps' in
 * file './hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'entrada_0', class 'entrada'
 * The macros are prefixed with 'ENTRADA_0_'.
 * The prefix is the slave descriptor.
 */
#define ENTRADA_0_COMPONENT_TYPE entrada
#define ENTRADA_0_COMPONENT_NAME entrada_0
#define ENTRADA_0_BASE 0x0
#define ENTRADA_0_SPAN 1
#define ENTRADA_0_END 0x0


#endif /* _ALTERA_HPS_0_H_ */
