#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps' in
 * file './hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fpga_to_hps', class 'altera_avalon_pio'
 * The macros are prefixed with 'FPGA_TO_HPS_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_TO_HPS_COMPONENT_TYPE altera_avalon_pio
#define FPGA_TO_HPS_COMPONENT_NAME fpga_to_hps
#define FPGA_TO_HPS_BASE 0x0
#define FPGA_TO_HPS_SPAN 16
#define FPGA_TO_HPS_END 0xf
#define FPGA_TO_HPS_BIT_CLEARING_EDGE_REGISTER 0
#define FPGA_TO_HPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FPGA_TO_HPS_CAPTURE 0
#define FPGA_TO_HPS_DATA_WIDTH 1
#define FPGA_TO_HPS_DO_TEST_BENCH_WIRING 0
#define FPGA_TO_HPS_DRIVEN_SIM_VALUE 0
#define FPGA_TO_HPS_EDGE_TYPE NONE
#define FPGA_TO_HPS_FREQ 50000000
#define FPGA_TO_HPS_HAS_IN 1
#define FPGA_TO_HPS_HAS_OUT 0
#define FPGA_TO_HPS_HAS_TRI 0
#define FPGA_TO_HPS_IRQ_TYPE NONE
#define FPGA_TO_HPS_RESET_VALUE 0

/*
 * Macros for device 'hps_to_fpga', class 'altera_avalon_pio'
 * The macros are prefixed with 'HPS_TO_FPGA_'.
 * The prefix is the slave descriptor.
 */
#define HPS_TO_FPGA_COMPONENT_TYPE altera_avalon_pio
#define HPS_TO_FPGA_COMPONENT_NAME hps_to_fpga
#define HPS_TO_FPGA_BASE 0x10
#define HPS_TO_FPGA_SPAN 16
#define HPS_TO_FPGA_END 0x1f
#define HPS_TO_FPGA_BIT_CLEARING_EDGE_REGISTER 0
#define HPS_TO_FPGA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HPS_TO_FPGA_CAPTURE 0
#define HPS_TO_FPGA_DATA_WIDTH 1
#define HPS_TO_FPGA_DO_TEST_BENCH_WIRING 0
#define HPS_TO_FPGA_DRIVEN_SIM_VALUE 0
#define HPS_TO_FPGA_EDGE_TYPE NONE
#define HPS_TO_FPGA_FREQ 50000000
#define HPS_TO_FPGA_HAS_IN 0
#define HPS_TO_FPGA_HAS_OUT 1
#define HPS_TO_FPGA_HAS_TRI 0
#define HPS_TO_FPGA_IRQ_TYPE NONE
#define HPS_TO_FPGA_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
