#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps' in
 * file './hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'key', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY_'.
 * The prefix is the slave descriptor.
 */
#define KEY_COMPONENT_TYPE altera_avalon_pio
#define KEY_COMPONENT_NAME key
#define KEY_BASE 0x0
#define KEY_SPAN 16
#define KEY_END 0xf
#define KEY_BIT_CLEARING_EDGE_REGISTER 0
#define KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY_CAPTURE 0
#define KEY_DATA_WIDTH 1
#define KEY_DO_TEST_BENCH_WIRING 0
#define KEY_DRIVEN_SIM_VALUE 0
#define KEY_EDGE_TYPE NONE
#define KEY_FREQ 50000000
#define KEY_HAS_IN 1
#define KEY_HAS_OUT 0
#define KEY_HAS_TRI 0
#define KEY_IRQ_TYPE NONE
#define KEY_RESET_VALUE 0

/*
 * Macros for device 'gpio_hps', class 'altera_avalon_pio'
 * The macros are prefixed with 'GPIO_HPS_'.
 * The prefix is the slave descriptor.
 */
#define GPIO_HPS_COMPONENT_TYPE altera_avalon_pio
#define GPIO_HPS_COMPONENT_NAME gpio_hps
#define GPIO_HPS_BASE 0x10
#define GPIO_HPS_SPAN 16
#define GPIO_HPS_END 0x1f
#define GPIO_HPS_BIT_CLEARING_EDGE_REGISTER 0
#define GPIO_HPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GPIO_HPS_CAPTURE 0
#define GPIO_HPS_DATA_WIDTH 1
#define GPIO_HPS_DO_TEST_BENCH_WIRING 0
#define GPIO_HPS_DRIVEN_SIM_VALUE 0
#define GPIO_HPS_EDGE_TYPE NONE
#define GPIO_HPS_FREQ 50000000
#define GPIO_HPS_HAS_IN 0
#define GPIO_HPS_HAS_OUT 1
#define GPIO_HPS_HAS_TRI 0
#define GPIO_HPS_IRQ_TYPE NONE
#define GPIO_HPS_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
